---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plexus-controller
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plexus.gg
  resources:
  - gameservers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plexus.gg
  resources:
  - gameservers/finalizers
  verbs:
  - update
- apiGroups:
  - plexus.gg
  resources:
  - gameservers/status
  verbs:
  - get
  - patch
  - update
