---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plexus-controller
  namespace: app-plexus
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - plexus.gg
  resources:
  - gameservers
  - saveexports
  - saveimports
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plexus.gg
  resources:
  - gameservers/finalizers
  - saveexports/finalizers
  - saveimports/finalizers
  verbs:
  - update
- apiGroups:
  - plexus.gg
  resources:
  - gameservers/status
  - saveexports/status
  - saveimports/status
  verbs:
  - get
  - patch
  - update
